spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petbutler?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: password

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql

  jwt:
    secret: cGV0YnV0bGVy

  mail:
    host: smtp.gmail.com
    port: 587
    username: simDev1234@gmail.com
    password: jetesonbvsyyapjx
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true

  redis:
    host: localhost
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:createAnimalHosptlJob}
      enabled: false
