spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: sa
    password:
    h2:
      console:
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: simDev1234@gmail.com
    password: wdrqocnckohduqzs
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true