server:
  port: 9000
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL;
    username: sa
  h2:
    console:
      enabled: true
    hikari:
      jdbc-url: jdbc:h2:mem:test;MODE=MYSQL
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: simDev1234@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true