spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petbutler?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: password
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: simDev1234@gmail.com
    password: jetesonbvsyyapjx
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      springframework: debug
      web: debug
